### ISSUE TITLE
EMLX Roadmap

### ISSUE THREAD

**Issue by samrat** [elixir-nx/emlx#5]
# EMLX Backend Callbacks Roadmap

**NOTE**: If you're grabbing one or more callbacks to tackle, please add a comment below so we don't have 2 people working on the same callback at the same time.

# Pending

- [ ] from_pointer
- [ ] to_pointer
- [x] window_scatter_max
- [x] window_scatter_min

LinAlg:
- [x] conv
- [x] lu
- [x] qr 
- [x] svd
- [x] triangular_solve
- [x] cholesky
- [x] eigh
- [x] solve
- [x] determinant

Not supported (just need to implement a nice error message):
- [x] count_leading_zeros
- [x] population_count
- [x] reduce
- [x] window_reduce

# Done

## Misc

- [x] to_batched
- [x] pad
- [x] reverse
- [x] put_slice
- [x] gather
- [x] phase
- [x] indexed_add
- [x] indexed_put
- [x] top_k
- [x] cbrt

## Setup & Manipulation
- [x] init
- [x] backend_deallocate
- [x] backend_copy  
- [x] backend_transfer

## Creation & Generators
- [x] constant
- [x] from_binary
- [x] eye
- [x] iota
- [x] to_binary
- [x] inspect

## Shape Operations  
- [x] as_type
- [x] bitcast
- [x] reshape 
- [x] squeeze
- [x] broadcast
- [x] transpose

## Element Access & Manipulation
- [x] slice
- [x] concatenate
- [x] stack
- [x] select 
- [x] take
- [x] take_along_axis

## Element-wise Binary Operations
- [x] add
- [x] subtract  
- [x] multiply
- [x] pow
- [x] remainder
- [x] divide
- [x] atan2
- [x] min
- [x] max
- [x] quotient
- [x] bitwise_and
- [x] bitwise_or  
- [x] bitwise_xor
- [x] left_shift
- [x] right_shift

## Element-wise Comparison Operations
- [x] equal
- [x] not_equal
- [x] greater
- [x] less
- [x] greater_equal 
- [x] less_equal
- [x] logical_and
- [x] logical_or
- [x] logical_xor

## Element-wise Unary Operations
- [x] abs
- [x] bitwise_not
- [x] ceil
- [x] conjugate  
- [x] floor
- [x] negate
- [x] round
- [x] sign
- [x] real
- [x] imag
- [x] is_nan
- [x] is_infinity
- [x] logical_not

## Reduction Operations
- [x] all
- [x] any
- [x] sum
- [x] product
- [x] reduce_max
- [x] reduce_min
- [x] argmax
- [x] argmin 
- [x] window_sum
- [x] window_product
- [x] window_max
- [x] window_min
- [x] cumulative_sum
- [x] cumulative_product
- [x] cumulative_min
- [x] cumulative_max

## Linear Algebra Operations
- [x] dot

## Sorting & Search Operations
- [x] sort
- [x] argsort

## FFT Operations
- [x] fft
- [x] ifft
- [x] fft2
- [x] ifft2

## Miscellaneous Operations
- [x] all_close
- [x] clip
